### ISSUE TITLE
The docker-compose up generates error on  partOne_Docker  branch

### ISSUE THREAD

**Issue by afattahi54** [eiselems/spring-boot-microservices#5]
The template-service is empty so could not run branch partOne_Docker 

````
git clone -b partOne_Docker https://github.com/eiselems/spring-boot-microservices.git
cd spring-boot-microservice
docker-compose up
````

Generates errors:

````

Step 3/5 : ADD target/template-service.jar app.jar
ERROR: Service 'template-service' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder799402977/target/template-service.jar: no such file or directory

````

**Comment by eiselems** [comment]
Grr I see, you are right. I am just thinking what would make the most sense for now. Initially I wanted to do the docker part together with the first service. Then I decided that it is enough to have its own chapter. Therefore I splitted it. Mhm how would you solve it? Make a hint that after the first part it is not booting because of the missing jar?

**Comment by eiselems** [comment]
Won't do ... ok part one is failing but future branches will work
