### ISSUE TITLE
counterservice  directly is not accessible

### ISSUE THREAD

**Issue by sudheer09** [eiselems/spring-boot-microservices#7]
Hi @eiselems ,

I tried in my local system  **http://localhost:8080/count** and it doesn't work.

As mentioned in Readme.md "_You also can access the counterservice itself directly at http://localhost:8080/count_" but counterservice is only accessible via zuul server which is **http://localhost:9999/api/cs/count**. url.

What kind of configuration has been made in code so that counterservice is not accessible directly ?

Thanks in advance!!

**Comment by eiselems** [comment]
Hi there,

Long time I touched this project.

I saw that the counter-service did crash because it couldn't connect to the config service.

I guess you were just seeing the login-page (which is served by Zuul).

Could you try to run

`docker-compose up` once more, after this happened?

For me this recreated the counterservice while the rest was already running.
Then http://localhost:8080/count should really show you something.

Also make sure not something else is running already on this port (sadly I have chosen a really common port for this project 😓 )

Let me know if that helped
